vim.keymap.set("n", "<Esc>", "<cmd>noh<CR>", { silent = true, noremap = true, desc = "clear highlights" })
vim.keymap.set("n", "<C-s>", "<cmd>silent! w<CR>", { silent = true, noremap = true, desc = "save file" })
vim.keymap.set("n", "<C-q>", "<cmd>q<CR>", { silent = true, noremap = true, desc = "quit file" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { silent = true, noremap = true, desc = "move to left window" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { silent = true, noremap = true, desc = "move to right window" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { silent = true, noremap = true, desc = "move to bottom window" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { silent = true, noremap = true, desc = "move to top window" })
vim.keymap.set("n", "<Tab>", "<cmd>bnext<CR>", { silent = true, noremap = true, desc = "next buffer" })
vim.keymap.set("n", "<S-Tab>", "<cmd>bprev<CR>", { silent = true, noremap = true, desc = "previous buffer" })
